// <auto-generated />
namespace Seekers.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removejopDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removejopDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201411232143244_remove jopDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
